### ISSUE TITLE
View config not found for name button

### ISSUE THREAD

**Issue by uguryiilmz** [daftcode/react-calendar-tutorial#2]
Hello,

I am new to React native and was trying to implement a calendar by looking at your article. First of all, thanks for your contribution and work. I made sure everything was the same as you did. However, I am getting an error called view config not found for name button in rendering part. Do you have any idea how could I solve it to integrate it with react native or does it matter if I use react-native instead of a browser? Thanks.

**Comment by adekbadek** [comment]
react-native is a much different environment than browser, so yeah, that could be the problem. But I can't say much without seeing the code - so you an repo for this project?

**Comment by uguryiilmz** [comment]
Thanks for replying quickly. I did pretty much the same thing as you did. I haven't changed it and i thought it should be compatible with React Native. Besides, I am also encountering an issue regarding google calendar. I am sending a request the same way you do by taking my api key and calendar id, but it throws me an error called Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup. I have been digging on the internet and people say i have to enable google calendar api from google developer console which I had already done.

**Comment by adekbadek** [comment]
I don't have experience with react-native so I won't be able to help :( 
As for the request problem, maybe try creating a new key?
